// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WebApplication10.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication10.model.Materialsimport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaterId")
                        .HasColumnType("integer");

                    b.Property<int>("MaterialtypeimportId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductmaterialsimportId")
                        .HasColumnType("integer");

                    b.Property<int>("min")
                        .HasColumnType("integer");

                    b.Property<int>("package")
                        .HasColumnType("integer");

                    b.Property<int>("price")
                        .HasColumnType("integer");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaterialtypeimportId");

                    b.HasIndex("ProductmaterialsimportId");

                    b.ToTable("materialsimports");
                });

            modelBuilder.Entity("WebApplication10.model.Materialtypeimport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("brak")
                        .HasColumnType("numeric");

                    b.Property<string>("typematerial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("materialtypeimports");
                });

            modelBuilder.Entity("WebApplication10.model.Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("partnetuId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("partnetuId");

                    b.ToTable("Orderss");
                });

            modelBuilder.Entity("WebApplication10.model.Productmaterialsimport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProducttypeimportId")
                        .HasColumnType("integer");

                    b.Property<string>("material")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("produczua")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("quantitymaterials")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProducttypeimportId");

                    b.ToTable("productmaterialsimports");
                });

            modelBuilder.Entity("WebApplication10.model.Productsimport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductmaterialsimportId")
                        .HasColumnType("integer");

                    b.Property<int>("articul")
                        .HasColumnType("integer");

                    b.Property<int>("cotrydnikiId")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("prise")
                        .HasColumnType("integer");

                    b.Property<string>("typeproduct")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductmaterialsimportId");

                    b.HasIndex("cotrydnikiId");

                    b.ToTable("productsimport");
                });

            modelBuilder.Entity("WebApplication10.model.Producttypeimport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrdersId")
                        .HasColumnType("integer");

                    b.Property<int>("coofizent")
                        .HasColumnType("integer");

                    b.Property<string>("tipproducts")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrdersId");

                    b.ToTable("producttypeimports");
                });

            modelBuilder.Entity("WebApplication10.model.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("WebApplication10.model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApplication10.model.cotrydniki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("family")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("helth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("pasport")
                        .HasColumnType("integer");

                    b.Property<int>("recvisitu")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("cotrydnikis");
                });

            modelBuilder.Entity("WebApplication10.model.partnetu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("inn")
                        .HasColumnType("integer");

                    b.Property<string>("locaciaproduct")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("phont")
                        .HasColumnType("integer");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("partnetus");
                });

            modelBuilder.Entity("WebApplication10.model.Materialsimport", b =>
                {
                    b.HasOne("WebApplication10.model.Materialtypeimport", "Materialtypeimport")
                        .WithMany("Materialsimports")
                        .HasForeignKey("MaterialtypeimportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication10.model.Productmaterialsimport", "productmaterialsimport")
                        .WithMany("materialsimports")
                        .HasForeignKey("ProductmaterialsimportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materialtypeimport");

                    b.Navigation("productmaterialsimport");
                });

            modelBuilder.Entity("WebApplication10.model.Orders", b =>
                {
                    b.HasOne("WebApplication10.model.partnetu", "partnetu")
                        .WithMany("Orderss")
                        .HasForeignKey("partnetuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("partnetu");
                });

            modelBuilder.Entity("WebApplication10.model.Productmaterialsimport", b =>
                {
                    b.HasOne("WebApplication10.model.Producttypeimport", "producttypeimport")
                        .WithMany("productmaterialsimports")
                        .HasForeignKey("ProducttypeimportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("producttypeimport");
                });

            modelBuilder.Entity("WebApplication10.model.Productsimport", b =>
                {
                    b.HasOne("WebApplication10.model.Productmaterialsimport", "productmaterialsimport")
                        .WithMany("productsimports")
                        .HasForeignKey("ProductmaterialsimportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication10.model.cotrydniki", "cotrydniki")
                        .WithMany("productsimport")
                        .HasForeignKey("cotrydnikiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cotrydniki");

                    b.Navigation("productmaterialsimport");
                });

            modelBuilder.Entity("WebApplication10.model.Producttypeimport", b =>
                {
                    b.HasOne("WebApplication10.model.Orders", "Orderss")
                        .WithMany("producttypeimports")
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orderss");
                });

            modelBuilder.Entity("WebApplication10.model.User", b =>
                {
                    b.HasOne("WebApplication10.model.Role", "Roles")
                        .WithMany("users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("WebApplication10.model.Materialtypeimport", b =>
                {
                    b.Navigation("Materialsimports");
                });

            modelBuilder.Entity("WebApplication10.model.Orders", b =>
                {
                    b.Navigation("producttypeimports");
                });

            modelBuilder.Entity("WebApplication10.model.Productmaterialsimport", b =>
                {
                    b.Navigation("materialsimports");

                    b.Navigation("productsimports");
                });

            modelBuilder.Entity("WebApplication10.model.Producttypeimport", b =>
                {
                    b.Navigation("productmaterialsimports");
                });

            modelBuilder.Entity("WebApplication10.model.Role", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("WebApplication10.model.cotrydniki", b =>
                {
                    b.Navigation("productsimport");
                });

            modelBuilder.Entity("WebApplication10.model.partnetu", b =>
                {
                    b.Navigation("Orderss");
                });
#pragma warning restore 612, 618
        }
    }
}
